[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    DFRobot/DFRobot_DF1201S
build_flags =
    -DUSER_SETUP_LOADED=1
    -include $PROJECT_DIR/User_Setup.h
    -DSD_CS=5
board_build.partitions = huge_app.csv
